#!/usr/bin/env bash

set -xeu
set -o pipefail

AGORA_VERSION=HEAD

GIT_DESCRIBE_OUT=`git describe --always`

if [ -n "$GIT_DESCRIBE_OUT" ]
then
	AGORA_VERSION=$GIT_DESCRIBE_OUT
fi

echo "Agora version is: $AGORA_VERSION"

docker build --build-arg AGORA_VERSION=$AGORA_VERSION -f $DOCKERFILE_PATH -t $IMAGE_NAME .
