#
# This configuration file is intended to provide a full node that follows
# TestNet and just validates / outputs what it sees.
#
# This configuration is provided for the convenience of developers and testers
# and should not be used where financial stakes are at stake.
# See `doc/config.example.yaml` in the Agora repository for a full,
# up to date example of the configuration options available
#
# Run from the root of Agora's repository, after building it, with:
# ./build/agora -c devel/testnet/config.yaml

node:
  realm: "testnet.bosagora.io"
  testing: true
  data_dir: .fullnode/data/
  registry_address: https://ns1.bosagora.io/

consensus:
  block_interval:
    seconds: 20
  validator_cycle: 20

registry:
  enabled: true

logging:
  root:
    # You might want to use `Trace` and separate output
    level: Info
    console: true
    propagate: true
    file: .fullnode/log/root.log
