#
# This configuration file is intended to provide a full node that follows
# the live system and just validates / outputs what it sees.
#
# This configuration is provided for the convenience of developers and should
# not be used in production. See `doc/config.example.yaml` for a full,
# up to date example of the configuration options available
#
# Run from the root with:
# ./build/agora -c devel/config-fullnode.yaml

node:
  realm: "testnet.bosagora.io"
  testing: true
  data_dir: .fullnode/data/
  # Can be used with curl or just a browser
  stats_listening_port: 9111

interfaces:
  - type:    http
    address: 0.0.0.0
    port:    2826

consensus:
  block_interval:
    seconds: 20
  validator_cycle: 20

validator:
  enabled: false
  registry_address: https://ns1.bosagora.io/

registry:
  enabled: true

logging:
  root:
    # You might want to use `Trace` and separate output
    level: Info
    console: true
    propagate: true
    file: .fullnode/log/root.log
